BIN      := datain
SRC_DIR  := ../../src/sources
SRC_FILES:= \
  sybie/datain/MainGen.cc \
  sybie/datain/Generate.cc \
  sybie/datain/Coding.cc \
  sybie/datain/Stream.cc \
  sybie/datain/Pool.cc \
  sybie/common/Arguments.cc \
  sybie/common/Event.cc \
  sybie/common/Streaming.cc \
  sybie/common/Text.cc \
  sybie/common/Time.cc \
  snappy/snappy.cc \
  snappy/snappy-sinksource.cc \
  snappy/snappy-stubs-internal.cc
CXXFLAGS := \
  -I../../include \
  -I../../src/headers \
  -I../../src/headers/snappy

include ../common/build.mk
